# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-05 21:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('reservation_date', models.DateTimeField(verbose_name='Date de réservation')),
                ('start_address', models.CharField(max_length=250, verbose_name='Adresse de départ')),
                ('dest_address', models.CharField(max_length=250, verbose_name='Adresse de destination')),
                ('state', models.BooleanField()),
                ('duration', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponibility', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='car',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='booking.Car'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
